package com.sunrise.dentalclinic.service;
import com.sunrise.dentalclinic.dto.AppointmentRequest;import com.sunrise.dentalclinic.exception.BusinessException;import com.sunrise.dentalclinic.model.*;import com.sunrise.dentalclinic.repository.AppointmentRepository;import org.junit.jupiter.api.*;import java.math.BigDecimal;import java.time.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class AppointmentServiceTest{AppointmentRepository repo;PatientService patients;DentistService dentists;TreatmentService treatments;AppointmentService service;Dentist dentist;Treatment treatment;Patient patient;LocalDate today=LocalDate.of(2026,9,3);
 @BeforeEach void setup(){repo=mock(AppointmentRepository.class);patients=mock(PatientService.class);dentists=mock(DentistService.class);treatments=mock(TreatmentService.class);service=new AppointmentService(repo,patients,dentists,treatments,Clock.fixed(today.atStartOfDay(ZoneId.of("Asia/Colombo")).toInstant(),ZoneId.of("Asia/Colombo")));patient=new Patient();dentist=new Dentist();treatment=new Treatment();treatment.setTreatmentCost(BigDecimal.TEN);when(patients.get(1L)).thenReturn(patient);when(dentists.get(2L)).thenReturn(dentist);when(treatments.get(3L)).thenReturn(treatment);when(repo.save(any())).thenAnswer(i->i.getArgument(0));}
 AppointmentRequest request(LocalDate date){return new AppointmentRequest(1L,2L,3L,date,LocalTime.of(10,0),"");}
 @Test void rejectsPastDate(){assertThrows(BusinessException.class,()->service.create(request(today.minusDays(1))));}
 @Test void preventsDoubleBooking(){when(repo.existsByDentistIdAndAppointmentDateAndAppointmentTimeAndStatusNotAndIdNot(any(),any(),any(),eq(AppointmentStatus.CANCELLED),any())).thenReturn(true);assertThrows(BusinessException.class,()->service.create(request(today)));}
 @Test void cancelledAppointmentDoesNotBlockSlot(){when(repo.existsByDentistIdAndAppointmentDateAndAppointmentTimeAndStatusNotAndIdNot(any(),any(),any(),eq(AppointmentStatus.CANCELLED),any())).thenReturn(false);assertDoesNotThrow(()->service.create(request(today)));}
 @Test void generatesAppointmentNumber(){var saved=service.create(request(today));assertTrue(saved.getAppointmentNumber().matches("APT-20260903-[0-9]{5}"));}}
