package com.sunrise.dentalclinic.service;
import com.sunrise.dentalclinic.dto.AppointmentRequest; import com.sunrise.dentalclinic.exception.*; import com.sunrise.dentalclinic.model.*; import com.sunrise.dentalclinic.repository.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*; import java.util.concurrent.ThreadLocalRandom;
@Service public class AppointmentService {
 private final AppointmentRepository repo; private final PatientService patients; private final DentistService dentists; private final TreatmentService treatments; private final Clock clock;
 @Autowired public AppointmentService(AppointmentRepository r,PatientService p,DentistService d,TreatmentService t){this(r,p,d,t,Clock.system(ZoneId.of("Asia/Colombo")));} AppointmentService(AppointmentRepository r,PatientService p,DentistService d,TreatmentService t,Clock c){repo=r;patients=p;dentists=d;treatments=t;clock=c;}
 @Transactional(readOnly=true) public List<Appointment> all(){return repo.findAll();} @Transactional(readOnly=true) public Appointment get(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Appointment not found"));}
 @Transactional(readOnly=true) public Appointment byNumber(String n){return repo.findByAppointmentNumberIgnoreCase(n).orElseThrow(()->new ResourceNotFoundException("Appointment not found"));}
 @Transactional public Appointment create(AppointmentRequest r){var a=new Appointment();a.setAppointmentNumber(nextNumber());apply(a,r);return repo.save(a);}
 @Transactional public Appointment update(Long id,AppointmentRequest r){var a=get(id);if(a.getStatus()!=AppointmentStatus.SCHEDULED)throw new BusinessException("Only scheduled appointments can be rescheduled");apply(a,r);return repo.save(a);}
 @Transactional public Appointment cancel(Long id){var a=get(id);a.setStatus(AppointmentStatus.CANCELLED);return repo.save(a);} @Transactional public Appointment complete(Long id){var a=get(id);if(a.getStatus()==AppointmentStatus.CANCELLED)throw new BusinessException("Cancelled appointments cannot be completed");a.setStatus(AppointmentStatus.COMPLETED);return repo.save(a);}
 private void apply(Appointment a,AppointmentRequest r){if(r.appointmentDate().isBefore(LocalDate.now(clock)))throw new BusinessException("Appointment date cannot be in the past");var d=dentists.get(r.dentistId());if(!d.isActive())throw new BusinessException("Selected dentist is inactive");var t=treatments.get(r.treatmentId());if(!t.isActive())throw new BusinessException("Selected treatment is inactive");Long id=a.getId()==null?-1L:a.getId();if(repo.existsByDentistIdAndAppointmentDateAndAppointmentTimeAndStatusNotAndIdNot(d.getId(),r.appointmentDate(),r.appointmentTime(),AppointmentStatus.CANCELLED,id))throw new BusinessException("Dentist is already booked for this time slot");a.setPatient(patients.get(r.patientId()));a.setDentist(d);a.setTreatment(t);a.setAppointmentDate(r.appointmentDate());a.setAppointmentTime(r.appointmentTime());a.setNotes(r.notes()==null?null:r.notes().trim());}
 String nextNumber(){for(int i=0;i<20;i++){String n="APT-"+LocalDate.now(clock).format(DateTimeFormatter.BASIC_ISO_DATE)+"-"+String.format("%05d",ThreadLocalRandom.current().nextInt(100000));if(!repo.existsByAppointmentNumber(n))return n;}throw new BusinessException("Could not generate appointment number; please retry");}
}
