package com.sunrise.dentalclinic;
import com.sunrise.dentalclinic.model.*;import com.sunrise.dentalclinic.repository.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.MockMvc;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Transactional
class BillingControllerTest{
 @Autowired MockMvc mvc;@Autowired PatientRepository patients;@Autowired DentistRepository dentists;@Autowired TreatmentRepository treatments;@Autowired AppointmentRepository appointments;Appointment appointment;
 @BeforeEach void data(){var p=new Patient();p.setName("Billing Patient");p.setAddress("Colombo");p.setContactNumber("0771234567");p=patients.save(p);var d=new Dentist();d.setName("Dr Billing");d.setSpecialization("General");d=dentists.save(d);var t=new Treatment();t.setTreatmentName("Cleaning");t.setTreatmentCost(new BigDecimal("2500.00"));t=treatments.save(t);appointment=new Appointment();appointment.setAppointmentNumber("APT-BILLING-TEST");appointment.setPatient(p);appointment.setDentist(d);appointment.setTreatment(t);appointment.setAppointmentDate(LocalDate.now().plusDays(1));appointment.setAppointmentTime(LocalTime.of(10,30));appointment.setStatus(AppointmentStatus.SCHEDULED);appointment=appointments.save(appointment);}
 @Test void loadsAppointmentsOnBillingPage()throws Exception{mvc.perform(get("/bills/new").with(user("staff").roles("STAFF"))).andExpect(status().isOk()).andExpect(view().name("bills/form")).andExpect(model().attributeExists("appointments")).andExpect(content().string(org.hamcrest.Matchers.containsString("APT-BILLING-TEST — Billing Patient")));}
 @Test void selectingAppointmentLoadsServerSidePreview()throws Exception{mvc.perform(get("/bills/new").param("appointmentId",appointment.getId().toString()).with(user("staff").roles("STAFF"))).andExpect(status().isOk()).andExpect(model().attributeExists("preview")).andExpect(content().string(org.hamcrest.Matchers.containsString("Dr Billing"))).andExpect(content().string(org.hamcrest.Matchers.containsString("LKR 3500.00")));}
}
